### ISSUE TITLE
下拉刷新完成过后的回弹动画有点问题

### ISSUE THREAD

**Issue by jamninetyfive** [bird-xiong/PTRScrollList#1]
下拉刷新完成过后的回弹动画有点问题

会经常布局回弹回去了 但是下拉刷新文字跟lottie 动画总会慢一点。。。

**Comment by bird-xiong** [comment]
> 下拉刷新完成过后的回弹动画有点问题
> 
> 会经常布局回弹回去了 但是下拉刷新文字跟lottie 动画总会慢一点。。。

iOS、 Android ？环境？

**Comment by bird-xiong** [comment]
最新代码增加了刷新成功停留时间的配置，关于手势冲突的问题可以给个demo给我，后面再优化一下
